name: Zip and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Zip File
      run: |
        zip -r mydataninja.zip .

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: mydataninja.zip
        tag_name: mydataninja@v5
        name: Release ${{ steps.get_commit.outputs.commit_sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}